#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: jessicasharman
  config:
    BUNDLE_WITHOUT: "development:test"
    # GOOGLE_ANALYTICS: "UA-50464982-1"
  addons:
    - pgbackups:auto-week

staging:
  app: jessicasharman-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
    # GOOGLE_ANALYTICS: 'UA-50464982-1'
    

# demo:
#   app: crowdscience-demo
#   config: *default


# rake production deploy 
